root: true

plugins:
  - babel

parser: babel-eslint

extends:
  - airbnb-base
  - plugin:prettier/recommended

env:
  es6: true
  node: true
  jest: true

rules:
  no-console: 'warn'
  import/no-default-export: 'error'
  import/prefer-default-export: 'off'
